import './globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Chris Duignan',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-[#0D0628] text-gray-50 lg:overflow-hidden h-screen'>
        {children}
      </body>
    </html>
  )
}
