name: 'main'

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run Lint
        run: npm run lint

  build:
    runs-on: ubuntu-latest
    needs: [lint]
    env:
      AIRTABLE_BASE: ${{ secrets.AIRTABLE_BASE }}
      AIRTABLE_TOKEN: ${{ secrets.AIRTABLE_TOKEN }}

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - name: Setup GCP SDK
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Configure Docker
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev 

      - name: Docker build
        run: docker buildx build --platform linux/amd64 -t portfolio .

      # - name: Docker tag
      # - run: docker tag port

  # terraform:
  #   runs-on: ubuntu-latest
  #   needs: [lint, build]
  #   defaults:
  #     run:
  #       working-directory: ./terraform

  #   permissions:
  #     contents: 'read'
  #     id-token: 'write'

  #   steps:
  #     - name: Checkout Repo
  #       uses: actions/checkout@v4
      
  #     - name: Authenticate to GCP
  #       uses: google-github-actions/auth@v1
  #       with:
  #         workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
  #         service_account: ${{ secrets.SERVICE_ACCOUNT }}

  #     - name: Setup Terraform
  #       uses: hashicorp/setup-terraform@v2
  #       with:
  #         terraform_version: "1.6.1"

  #     - name: Terraform Format
  #       run: terraform fmt -check

  #     - name: Terraform Init
  #       run: terraform init

  #     - name: Terraform Validate
  #       run: terraform validate

  #     - name: Terraform Plan
  #       run: terraform plan -input=false -out=tfplan

  #     - name: Terraform Apply
  #       run: terraform apply -input=false tfplan

      